package com.clawkit.ops.delivery;

/**
 * Historical standalone repair launcher retained only as a fail-closed
 * compatibility entry point.
 *
 * <p>CLAWKIT's current product paths are remote-read-only. Keeping a dormant
 * implementation here would make it too easy for a future wiring change to
 * bypass the CLI's read-only profile, A2 approval path, or the A4 No-Go
 * decision. Fixture approval evidence is generated by {@link FixtureAskEvidenceMain}.
 */
public final class RemoteIncidentRepairMain {

    private RemoteIncidentRepairMain() {}

    public static void main(String[] args) {
        System.exit(run(args));
    }

    static int run(String[] args) {
        System.err.println("Remote repair is disabled: current CLAWKIT product paths are read-only; "
            + "use the disposable Fixture approval tests for A2 evidence.");
        return 2;
    }
}
